In [1]:
import numpy as np

In [2]:
array = np.array([10, 20, 30, 40, 50])
array

array([10, 20, 30, 40, 50])

In [3]:
#Pesquisar a posição valor 30
posicao = np.where(array==30)
posicao

(array([2], dtype=int64),)

In [4]:
#Criar um array com notas de alunos
notas = np.array([55, 67, 72, 48, 90, 85, 60, 50])
notas

array([55, 67, 72, 48, 90, 85, 60, 50])

In [5]:
#Pesquisar quais alunos foram aprovados (nota > 60)
alunos_aprovados = np.where(notas > 60)
alunos_aprovados

(array([1, 2, 4, 5], dtype=int64),)

In [6]:
notas[alunos_aprovados]

array([67, 72, 90, 85])

In [7]:
nota_maxima = np.max(notas)
nota_maxima

90

In [8]:
indice_maximo = np.argmax(notas)
indice_maximo

4