In [1]:
import numpy as np

In [3]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim) # Número de dimensões
print(array_1d.shape) # Formato do array
array_1d
# Lista de Dados, como séries temporais ou coleções de valores

1
(5,)


array([1, 2, 3, 4, 5])

In [4]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim) # Número de dimensões
print(array_2d.shape) # Formato do array
array_2d
# Matrizes, tabelas de dados, imagens em escala de cinza

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(array_3d.ndim) # Número de dimensões
print(array_3d.shape) # Formato do array
array_3d
# Imagens em cores (cada matriz representando um canal de cor, como RGB)

3
(1, 4, 2)


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [6]:
array_4d = np.zeros((2, 3, 4, 5))
print(array_4d.ndim) # Número de dimensões
print(array_4d.shape) # Formato do array
array_4d

4
(2, 3, 4, 5)


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])