In [1]:
import numpy as np

In [3]:
array = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
print(array.ndim)
print(array.shape)
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [4]:
# Buscar elemento na linha 1 e coluna 2
elemento = array[1, 2]
elemento

60

In [5]:
# Pegar dados da primeira linha
linha_0 = array[0]
linha_0

array([10, 20, 30])

In [6]:
# Acessando a coluna 1
coluna_1 = array[:, 1]
coluna_1

array([20, 50, 80])

In [7]:
# Fatiando para obter um subarray
# Linha 0 a 1 | Coluna 1 a 2
subarray = array[0:2, 1:3]
subarray

array([[20, 30],
       [50, 60]])

In [8]:
mascara = array > 50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [9]:
elementos_maiores_que_50 = array[mascara]
elementos_maiores_que_50

array([60, 70, 80, 90])

In [10]:
# Modificando elemento na linha 1, coluna 1
array[1, 1] = 100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])